-- Temporarily disable RLS for development
-- Copy and paste this into Supabase SQL Editor and run it

ALTER TABLE course_enrollments DISABLE ROW LEVEL SECURITY;
ALTER TABLE event DISABLE ROW LEVEL SECURITY;
ALTER TABLE lesson DISABLE ROW LEVEL SECURITY;
ALTER TABLE course DISABLE ROW LEVEL SECURITY;
ALTER TABLE room DISABLE ROW LEVEL SECURITY;
ALTER TABLE facility DISABLE ROW LEVEL SECURITY;
