-- Disable RLS for development
ALTER TABLE IF EXISTS course_enrollments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS event DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS lesson DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS course DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS room DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS facility DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "user" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS assignment DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS submission DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS announcement DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS material DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS course_materials DISABLE ROW LEVEL SECURITY;
